## Data Encoding

#### 1. Nominal/OHE Encoding
#### 2. Label and Ordinal Encoding
#### 3. Target Guided Ordinal Encoding

## Nominal/OHE Encoding

One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more
suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a
unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it
one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# create the  simple data frame 
df = pd.DataFrame({
    'color': ['red','blue','green','red','green','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3    red
4  green

In [5]:
df.tail()

   color
1   blue
2  green
3    red
4  green
5   blue

In [6]:
# Create a instance of onehotEncoder
encoder = OneHotEncoder()

In [9]:
## Perform fit and Transform 
encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [15]:
# converting into 2 array 

encoded = encoder.fit_transform(df[['color']]).toarray()
print(encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

In [16]:
import pandas as pd
encoder_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [17]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0
5         1.0          0.0        0.0

In [51]:
# for new Data 
encoder.transform([['blue']]).toarray()

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [19]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4  green         0.0          1.0        0.0
5   blue         1.0          0.0        0.0

In [24]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
import seaborn as sns 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [27]:
df = sns.load_dataset('tips')

In [28]:
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
lable = LabelEncoder()

df['sex_encoder'] = lable.fit_transform(df['sex'])
df['smoker_encoder'] = lable.fit_transform(df['smoker'])
df['timer_encoder'] = lable.fit_transform(df['time'])

In [35]:
df = pd.get_dummies(df, columns=['day'], drop_first=True)

In [36]:
df.drop(['sex','smoker','time'], axis=1, inplace=True)
print(df.head())

   total_bill   tip  size  sex_encoder  smoker_encoder  day_encoder  \
0       16.99  1.01     2            0               0            2
1       10.34  1.66     3            1               0            2
2       21.01  3.50     3            1               0            2
3       23.68  3.31     2            1               0            2
4       24.59  3.61     4            0               0            2

   timer_encoder  day_Fri  day_Sat  day_Sun
0              0    False    False     True
1              0    False    False     True
2              0    False    False     True
3              0    False    False     True
4              0    False    False     True

### Label Encoding

#### Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical
order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green,
blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
lbl_Encoder = LabelEncoder()

In [47]:
lbl_Encoder.fit_transform(df[['size']])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 2, 2, 1, 3, 3, 1, 3, 1, 1, 1, 3, 1, 3, 1, 1, 2, 2, 2, 2, 1, 1,
       1, 3, 1, 3, 1, 1, 1, 1, 1, 3, 1, 3, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       3, 1, 1, 3, 2, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 3, 1, 1, 1, 3, 2, 2,
       1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 0, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 2, 1, 2, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 5, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 4, 5, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3,
       3, 4, 5, 3, 1, 3, 3, 1, 2, 1, 1, 2, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 1, 2, 3, 1, 4, 2, 4, 2, 2, 1, 1, 1, 1, 1, 1, 1, 3,
       1, 1, 2, 1, 1, 1, 3, 2, 2, 3, 1, 1, 2, 3, 3, 1, 2, 1, 4, 1, 1, 3,
       1, 1, 0, 2, 1, 1, 1, 3, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 1])

In [48]:
lbl_Encoder.transform([[3]])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [49]:
lbl_Encoder.transform([[2]])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [50]:
lbl_Encoder.transform([[4]])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([3])

## Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value
based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school,
college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [52]:
from sklearn.preprocessing import  OrdinalEncoder

In [53]:
# create the data frame with an ordinal variable
df = pd.DataFrame({
        'size':['small','medium','large','medium','small','large']
})

In [54]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [56]:
## create an instance of ORdinalEncoder and then fit_transform

encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [57]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [58]:
encoder.transform([['small']])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [59]:
encoder.transform([['medium']])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

In [60]:
encoder.transform([['large']])

C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

### Target Guided Ordinal Encoding
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful
when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine
learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median
of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which
can improve the predictive power of our model.

In [61]:
import pandas as pd

In [67]:

# creating a sample dataframe with a categorical variable and a target variable

df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'Price':[200,150,300,250,180,380]

})

In [68]:
df

       city  Price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    380

In [74]:
mean_price = df.groupby('city')['Price'].mean().to_dict()

In [75]:
print(mean_price)

{'London': 150.0, 'New York': 190.0, 'Paris': 340.0, 'Tokyo': 250.0}

In [77]:
df['city_encoded'] = df['city'].map(mean_price)

In [78]:
df['city_encoded']

0    190.0
1    150.0
2    340.0
3    250.0
4    190.0
5    340.0
Name: city_encoded, dtype: float64

In [79]:
df

       city  Price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         340.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    380         340.0

In [83]:
import seaborn as sns 
import pandas as pd
df = sns.load_dataset('tips')

In [84]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [85]:
mean_bill = df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\Laptop\AppData\Local\Temp\ipykernel_39216\3722957593.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = df.groupby('time')['total_bill'].mean().to_dict()

In [86]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [87]:
df['time_encoded'] = df['time'].map(mean_bill)

In [88]:
df['time_encoded']

0      20.797159
1      20.797159
2      20.797159
3      20.797159
4      20.797159
         ...
239    20.797159
240    20.797159
241    20.797159
242    20.797159
243    20.797159
Name: time_encoded, Length: 244, dtype: category
Categories (2, float64): [17.168676, 20.797159]

In [89]:
df[['time', 'total_bill', 'time_encoded']].head()

     time  total_bill time_encoded
0  Dinner       16.99    20.797159
1  Dinner       10.34    20.797159
2  Dinner       21.01    20.797159
3  Dinner       23.68    20.797159
4  Dinner       24.59    20.797159