## Pandas-DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It
provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object,
while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure
with labeled axes (rows and columns).

In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Laptop\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import panda as pd

In [ ]:
# series 
# it is a one dimensional data type that can create easily 
import pandas as pd
data = [1,2,3,4,5,6,7,8,9]
series = pd.Series(data)
print("series",series)

series 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [3]:
# create the series from dictionary 
import pandas as pd
data={'a':1,'b':2,'c':3,'d':4,'e':5}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
data = [1,2,3,4]
index = ['a','b','c','d']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
dtype: int64

## DataFrames

In [6]:
# Create the dataframe from  a dictionary of list 

data={
'Name' : ['Krish', ' John', ' Jack' ],
'Age': [25,30,45],
'City': ['Bangalore', 'New York', 'Florida']

}
df = pd.DataFrame(data)
print(df)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [7]:
# Create the data frames using  a list of Dictonary 

data = [
        {'Name': 'Krish', 'Age': 32, 'City': 'Bangalore'},
        {'Name': 'Ansh', 'Age': 19, 'City': 'delhi'},
        {'Name' : 'Anuj', 'Age' :20,'City':'pune'},
        {'Name': 'Abhay', 'Age': 21, 'City': 'Bangalore'},
        {'Name': 'Ashish', 'Age': 23, 'City': 'jaipur'},


]
df = pd.DataFrame(data)
print(df)

     Name  Age       City
0   Krish   32  Bangalore
1    Ansh   19      delhi
2    Anuj   20       pune
3   Abhay   21  Bangalore
4  Ashish   23     jaipur

In [10]:
df['Name']
df.iloc[0,2]

'Bangalore'

In [11]:
# acessing the specified elements

df['Name']

0     Krish
1      Ansh
2      Anuj
3     Abhay
4    Ashish
Name: Name, dtype: object

In [15]:
# data manupulation with data frames
df

     Name  Age       City
0   Krish   32  Bangalore
1    Ansh   19      delhi
2    Anuj   20       pune
3   Abhay   21  Bangalore
4  Ashish   23     jaipur

In [16]:
df['salary']=[10000,20000,30000,20000,10000]

In [17]:
df

     Name  Age       City  salary
0   Krish   32  Bangalore   10000
1    Ansh   19      delhi   20000
2    Anuj   20       pune   30000
3   Abhay   21  Bangalore   20000
4  Ashish   23     jaipur   10000

In [ ]:
# remove the column 
df.drop('salary',axis=1,inplace=True)

In [24]:
df

     Name  Age       City
0   Krish   32  Bangalore
1    Ansh   19      delhi
2    Anuj   20       pune
3   Abhay   21  Bangalore
4  Ashish   23     jaipur

In [25]:
# add age to the column 
df['Age']=df['Age']+1

In [26]:
df

     Name  Age       City
0   Krish   33  Bangalore
1    Ansh   20      delhi
2    Anuj   21       pune
3   Abhay   22  Bangalore
4  Ashish   24     jaipur

In [27]:
df.drop(0)

     Name  Age       City
1    Ansh   20      delhi
2    Anuj   21       pune
3   Abhay   22  Bangalore
4  Ashish   24     jaipur