## Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a
wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract
insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [28]:
import pandas as pd

In [29]:

df = pd.read_csv('sample_data_100.csv')

In [30]:
print(df.shape)

(100, 6)

In [31]:
df.tail()

          Date Category  Value   Product  Sales Region
95  2023-04-06        C   71.7  Product1  667.6   West
96  2023-04-07        A   17.0  Product1  792.5  North
97  2023-04-08        B   69.8  Product1  300.6  North
98  2023-04-09        C   99.9  Product2  209.0  North
99  2023-04-10        C   85.9  Product3  389.6  North

In [32]:
df.describe()

            Value      Sales
count  100.000000  100.00000
mean    53.136000  493.23700
std     25.318195  220.90954
min      6.700000  119.90000
25%     31.650000  300.15000
50%     55.150000  487.00000
75%     75.450000  674.85000
max     99.900000  893.00000

In [33]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        B   31.7  Product3  305.0  South
1  2023-01-02        C   20.6  Product2  673.8   West
2  2023-01-03        B   64.9  Product1  642.4   West
3  2023-01-04        A   91.3  Product3  544.3   East
4  2023-01-05        B   46.0  Product1  255.5  South

In [34]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [35]:
## Handling missing values 
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [36]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [37]:
# change the data type of date

df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [38]:
df = df.rename(columns = {'Date':'Sales Date'})
df.head()

   Sales Date Category  Value   Product  Sales Region
0  2023-01-01        B   31.7  Product3  305.0  South
1  2023-01-02        C   20.6  Product2  673.8   West
2  2023-01-03        B   64.9  Product1  642.4   West
3  2023-01-04        A   91.3  Product3  544.3   East
4  2023-01-05        B   46.0  Product1  255.5  South

In [39]:
df['New Value']=df['Value'].apply(lambda x:x*2)

In [40]:
df.head()

   Sales Date Category  Value   Product  Sales Region  New Value
0  2023-01-01        B   31.7  Product3  305.0  South       63.4
1  2023-01-02        C   20.6  Product2  673.8   West       41.2
2  2023-01-03        B   64.9  Product1  642.4   West      129.8
3  2023-01-04        A   91.3  Product3  544.3   East      182.6
4  2023-01-05        B   46.0  Product1  255.5  South       92.0

In [41]:
# Date Aggrigation and Groupping 

df.head()

   Sales Date Category  Value   Product  Sales Region  New Value
0  2023-01-01        B   31.7  Product3  305.0  South       63.4
1  2023-01-02        C   20.6  Product2  673.8   West       41.2
2  2023-01-03        B   64.9  Product1  642.4   West      129.8
3  2023-01-04        A   91.3  Product3  544.3   East      182.6
4  2023-01-05        B   46.0  Product1  255.5  South       92.0

In [42]:
grouped_mean=df.groupby('Product') ['Value' ].mean()
print(grouped_mean)

Product
Product1    49.488235
Product2    56.858621
Product3    53.570270
Name: Value, dtype: float64

In [44]:
grouped_sum=df.groupby(['Product', 'Region' ]) ['Value' ] . sum()
print(grouped_sum)

Product   Region
Product1  East      427.8
          North     429.9
          South     456.0
          West      368.9
Product2  East      255.4
          North     652.2
          South     329.6
          West      411.7
Product3  East      351.8
          North     680.2
          South     456.2
          West      493.9
Name: Value, dtype: float64

In [47]:
# agregate multiple functions 

grouped_agg=df.groupby('Region')['Value' ].agg(['mean','sum','count'])
grouped_agg

             mean     sum  count
Region
East    49.285714  1035.0     21
North   56.848387  1762.3     31
South   53.991304  1241.8     23
West    50.980000  1274.5     25

In [48]:
# merging and joining DataFrame

df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key':['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [49]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [50]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [54]:
# merege the Dataframe on the key column 
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
# on="ID" — yeh batata hai ki kaunse column se dono tables ko jodna hai. Dono tables mein ID column common tha, toh on="ID" likha.
# how="inner" — yeh batata hai kaise jodna hai:

# inner → sirf common rows
# left → df1 ki sab rows + match wali df2 ki rows
# right → df2 ki sab rows + match wali df1 ki rows
# outer → dono ki sab rows, missing mein NaN

In [55]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [56]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [57]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6